name: Test django-override-autonow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        django-version: ['2.2', '3.0', '3.1', '3.2', '4.0']
        exclude:
            - python-version: '3.7'
              django-version: '4.0'

    name: Test on Python${{ matrix.python-version }} -- Django${{ matrix.django-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools flake8 pytest pytest-django
          python -m pip install "Django==${{ matrix.django-version }}"
          python -m pip install .
      - name: Lint with flake8
        run: |
          flake8 src tests
      - name: Test with pytest
        env:
          DJANGO_SETTINGS_MODULE: tests.testapp.settings
        run: |
          pytest tests -v

  test-packaging:
    runs-on: ubuntu-latest
    name: Test packaging
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build twine
      - name: Build and check
        run: |
          python -m build
          python -m twine check dist/*
